{
 "title": "Donovan | Completo 10",
 "time": { "from": "now-12h", "to": "now+6h" },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "db_rem",
     "rawSql": "SELECT \n  CASE \n    WHEN max(fecha_hora) >= now() - INTERVAL '30 minutes' THEN 1 \n    ELSE 0 \n  END as estado\nFROM datos_rem_temp\nWHERE id_estacion = 85;"
    }
   ]
  },
  {
   "title": "Temperatura Actual",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "db_rem",
     "rawSql": "SELECT\n  temperatura AS \"value\"\nFROM datos_rem_temp\nWHERE id_estacion = 85\nORDER BY fecha_hora DESC\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "Humedad Actual",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "db_rem",
     "rawSql": "SELECT humedad as \"value\" \nFROM datos_rem_temp \nWHERE id_estacion = 85 \nORDER BY fecha_hora DESC LIMIT 1;"
    }
   ]
  },
  {
   "title": "Vel. del Viento Actual",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "db_rem",
     "rawSql": "SELECT (viento_velocidad * 3.6) \nFROM datos_rem_temp \nWHERE id_estacion = 85 \nORDER BY fecha_hora DESC LIMIT 1;"
    }
   ]
  },
  {
   "title": "Dir. del Viento Actual",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "db_rem",
     "rawSql": "SELECT \n  viento_direccion AS \"value\" \nFROM \n  datos_rem_temp \nWHERE \n  id_estacion = 85 \nORDER BY \n  fecha_hora DESC \nLIMIT 1;"
    }
   ]
  },
  {
   "title": "+1H",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT temperatura_predicha FROM predicciones_temperatura WHERE id_estacion = 85 AND modelo = 1 AND horizonte = 1 AND fecha_generacion = (SELECT MAX(fecha_generacion) FROM predicciones_temperatura WHERE id_estacion = 85 AND modelo = 1) LIMIT 1;"
    }
   ]
  },
  {
   "title": "+2H",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT temperatura_predicha FROM predicciones_temperatura WHERE id_estacion = 85 AND modelo = 1 AND horizonte = 2 AND fecha_generacion = (SELECT MAX(fecha_generacion) FROM predicciones_temperatura WHERE id_estacion = 85 AND modelo = 1) LIMIT 1;"
    }
   ]
  },
  {
   "title": "+3H",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT temperatura_predicha FROM predicciones_temperatura WHERE id_estacion = 85 AND modelo = 1 AND horizonte = 3 AND fecha_generacion = (SELECT MAX(fecha_generacion) FROM predicciones_temperatura WHERE id_estacion = 85 AND modelo = 1) LIMIT 1;"
    }
   ]
  },
  {
   "title": "+4H",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT temperatura_predicha FROM predicciones_temperatura WHERE id_estacion = 85 AND modelo = 1 AND horizonte = 4 AND fecha_generacion = (SELECT MAX(fecha_generacion) FROM predicciones_temperatura WHERE id_estacion = 85 AND modelo = 1) LIMIT 1;"
    }
   ]
  },
  {
   "title": "+5H",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT temperatura_predicha FROM predicciones_temperatura WHERE id_estacion = 85 AND modelo = 1 AND horizonte = 5 AND fecha_generacion = (SELECT MAX(fecha_generacion) FROM predicciones_temperatura WHERE id_estacion = 85 AND modelo = 1) LIMIT 1;"
    }
   ]
  },
  {
   "title": "+6H",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT temperatura_predicha FROM predicciones_temperatura WHERE id_estacion = 85 AND modelo = 1 AND horizonte = 6 AND fecha_generacion = (SELECT MAX(fecha_generacion) FROM predicciones_temperatura WHERE id_estacion = 85 AND modelo = 1) LIMIT 1;"
    }
   ]
  },
  {
   "title": "ALERTA VIENTO NORTE / OESTE",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH alerta_reciente AS (\n  SELECT \n    '⚠️ ALERTA (' || TO_CHAR(fecha_hora_alerta, 'HH24:MI') || 'h)' as estado,\n    ROUND(velocidad_viento * 3.6, 1) || ' km/h' as velocidad\n  FROM alertas_viento \n  WHERE id_estacion = 22 \n    AND fecha_hora_alerta >= (NOW() - INTERVAL '12 hours')\n  ORDER BY fecha_hora_alerta DESC \n  LIMIT 1\n)\nSELECT estado, velocidad FROM alerta_reciente\nUNION ALL\nSELECT 'SIN ALERTA', ''\nWHERE NOT EXISTS (SELECT 1 FROM alerta_reciente)\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "ALERTA VIENTO SUR ",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "(\r\n    SELECT \r\n        '⚠️ ALERTA (' || TO_CHAR(fecha_hora_alerta, 'HH24:MI') || 'h)' as \"E\", \r\n        ROUND(velocidad_viento * 3.6, 1) || ' km/h' as \"V\"\r\n    FROM alertas_viento\r\n    WHERE id_estacion IN (26, 52, 14)\r\n      AND fecha_hora_alerta >= NOW() - INTERVAL '12 hours'\r\n    ORDER BY fecha_hora_alerta DESC\r\n    LIMIT 1\r\n)\r\nUNION ALL\r\nSELECT 'SIN ALERTA', ''\r\nWHERE NOT EXISTS (\r\n    SELECT 1 \r\n    FROM alertas_viento\r\n    WHERE id_estacion IN (26, 52, 14)\r\n      AND fecha_hora_alerta >= NOW() - INTERVAL '12 hours'\r\n)\r\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "Temperatura - Prediccion en Donovan",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "dataset": "db_rem",
     "rawSql": "SELECT\n    fecha_pronostico AS time,\n    temperatura_predicha AS \"Modelo 1\"\nFROM predicciones_temperatura\nWHERE id_estacion = 85\n  AND modelo = 1\n  AND fecha_generacion = (\n      SELECT MAX(fecha_generacion) FROM predicciones_temperatura\n      WHERE id_estacion = 85 AND modelo = 1\n  )\nORDER BY time ASC"
    },
    {
     "dataset": "db_rem",
     "rawSql": "SELECT\n  fecha_hora AT TIME ZONE 'America/Argentina/Buenos_Aires' AS \"time\",\n  temperatura AS \"Temp Historico\",\n  'Temperatura Real' AS \"metric\"\nFROM public.datos_rem \nWHERE id_estacion = 85 \n  AND $__timeFilter(fecha_hora)\nORDER BY fecha_hora ASC;"
    },
    {
     "dataset": "db_rem",
     "rawSql": "SELECT\n  fecha_hora AT TIME ZONE 'America/Argentina/Buenos_Aires' AS \"time\",\n  temperatura AS \"Temp Actual\",\n  'Temp Real (10 min)' AS \"metric\"\nFROM datos_rem_temp\nWHERE id_estacion = 85\n  -- La magia está aquí: Solo trae datos mayores al último registro de la tabla por hora\n  AND fecha_hora > (SELECT MAX(fecha_hora) FROM public.datos_rem WHERE id_estacion = 85)\n  AND $__timeFilter(fecha_hora)\nORDER BY fecha_hora ASC;"
    },
    {
     "dataset": "db_rem",
     "rawSql": "SELECT\r\n    fecha_pronostico AS time,\r\n    temperatura_predicha AS \"Modelo 3\"\r\nFROM predicciones_temperatura\r\nWHERE id_estacion = 85\r\n  AND modelo = 3\r\n  AND fecha_generacion = (\r\n      SELECT MAX(fecha_generacion) FROM predicciones_temperatura\r\n      WHERE id_estacion = 85 AND modelo = 3\r\n  )\r\nORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Fecha del patron mas parecido",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "db_rem",
     "rawSql": "SELECT \n  fecha_inicio_analogo \nFROM \n  analogos_temperatura \nWHERE \n  rank_analogo = 1\nORDER BY \n  fecha_generacion DESC \nLIMIT 1;"
    }
   ]
  },
  {
   "title": "Patron mas Parecido",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "rawSql": "SELECT\n    fecha_generacion + (hora_ventana * INTERVAL '1 hour') \n        - (360 * INTERVAL '1 hour') AS time,\n    temp_actual AS \"Ventana Actual\",\n    temp_analogo AS \"Análogo 1\"\nFROM analogos_temperatura\nWHERE id_estacion = 85\n  AND rank_analogo = 1\n  AND fecha_generacion = (\n      SELECT MAX(fecha_generacion)\n      FROM analogos_temperatura\n      WHERE id_estacion = 85\n  )\nORDER BY hora_ventana ASC"
    }
   ]
  }
 ]
}